### ISSUE TITLE
Code standaarden

### ISSUE THREAD

**Issue by Jeroen777** [Jeroen777/Foodie#19]
Even opletten er staan nu op meerdere plekken code afgesloten met ;

https://github.com/Jeroen777/Foodie/blob/6248dff06fe4bfb77a426ba64b33f957ea2d30de/server.js#L201-L219

**Comment by MariaS20** [comment]
Ja gaan we even naar kijken

**Comment by hihijenny** [comment]
het spijt me, ga het aanpassen

**Comment by hihijenny** [comment]
Alles is aangepast.
